/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnimalTypesRouteImport } from './routes/dashboard/animal-types'
import { Route as DashboardBackupRouteImport } from './routes/dashboard/backup'
import { Route as DashboardClansRouteImport } from './routes/dashboard/clans'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard/groups'
import { Route as DashboardHandoversRouteImport } from './routes/dashboard/handovers'
import { Route as DashboardLoansRouteImport } from './routes/dashboard/loans'
import { Route as DashboardObligationsRouteImport } from './routes/dashboard/obligations'
import { Route as DashboardParticipantsRouteImport } from './routes/dashboard/participants'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardReceiptsRouteImport } from './routes/dashboard/receipts'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSyncRouteImport } from './routes/dashboard/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnimalTypesRoute = DashboardAnimalTypesRouteImport.update({
  id: '/animal-types',
  path: '/animal-types',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBackupRoute = DashboardBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClansRoute = DashboardClansRouteImport.update({
  id: '/clans',
  path: '/clans',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHandoversRoute = DashboardHandoversRouteImport.update({
  id: '/handovers',
  path: '/handovers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLoansRoute = DashboardLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardObligationsRoute = DashboardObligationsRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardParticipantsRoute = DashboardParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReceiptsRoute = DashboardReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSyncRoute = DashboardSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/animal-types': typeof DashboardAnimalTypesRoute
  '/dashboard/backup': typeof DashboardBackupRoute
  '/dashboard/clans': typeof DashboardClansRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/handovers': typeof DashboardHandoversRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/obligations': typeof DashboardObligationsRoute
  '/dashboard/participants': typeof DashboardParticipantsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/animal-types': typeof DashboardAnimalTypesRoute
  '/dashboard/backup': typeof DashboardBackupRoute
  '/dashboard/clans': typeof DashboardClansRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/handovers': typeof DashboardHandoversRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/obligations': typeof DashboardObligationsRoute
  '/dashboard/participants': typeof DashboardParticipantsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/animal-types': typeof DashboardAnimalTypesRoute
  '/dashboard/backup': typeof DashboardBackupRoute
  '/dashboard/clans': typeof DashboardClansRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/handovers': typeof DashboardHandoversRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/obligations': typeof DashboardObligationsRoute
  '/dashboard/participants': typeof DashboardParticipantsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/animal-types'
    | '/dashboard/backup'
    | '/dashboard/clans'
    | '/dashboard/groups'
    | '/dashboard/handovers'
    | '/dashboard/loans'
    | '/dashboard/obligations'
    | '/dashboard/participants'
    | '/dashboard/profile'
    | '/dashboard/receipts'
    | '/dashboard/settings'
    | '/dashboard/sync'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/animal-types'
    | '/dashboard/backup'
    | '/dashboard/clans'
    | '/dashboard/groups'
    | '/dashboard/handovers'
    | '/dashboard/loans'
    | '/dashboard/obligations'
    | '/dashboard/participants'
    | '/dashboard/profile'
    | '/dashboard/receipts'
    | '/dashboard/settings'
    | '/dashboard/sync'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/animal-types'
    | '/dashboard/backup'
    | '/dashboard/clans'
    | '/dashboard/groups'
    | '/dashboard/handovers'
    | '/dashboard/loans'
    | '/dashboard/obligations'
    | '/dashboard/participants'
    | '/dashboard/profile'
    | '/dashboard/receipts'
    | '/dashboard/settings'
    | '/dashboard/sync'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/animal-types': {
      id: '/dashboard/animal-types'
      path: '/animal-types'
      fullPath: '/dashboard/animal-types'
      preLoaderRoute: typeof DashboardAnimalTypesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/backup': {
      id: '/dashboard/backup'
      path: '/backup'
      fullPath: '/dashboard/backup'
      preLoaderRoute: typeof DashboardBackupRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clans': {
      id: '/dashboard/clans'
      path: '/clans'
      fullPath: '/dashboard/clans'
      preLoaderRoute: typeof DashboardClansRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/handovers': {
      id: '/dashboard/handovers'
      path: '/handovers'
      fullPath: '/dashboard/handovers'
      preLoaderRoute: typeof DashboardHandoversRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/loans': {
      id: '/dashboard/loans'
      path: '/loans'
      fullPath: '/dashboard/loans'
      preLoaderRoute: typeof DashboardLoansRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/obligations': {
      id: '/dashboard/obligations'
      path: '/obligations'
      fullPath: '/dashboard/obligations'
      preLoaderRoute: typeof DashboardObligationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/participants': {
      id: '/dashboard/participants'
      path: '/participants'
      fullPath: '/dashboard/participants'
      preLoaderRoute: typeof DashboardParticipantsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/receipts': {
      id: '/dashboard/receipts'
      path: '/receipts'
      fullPath: '/dashboard/receipts'
      preLoaderRoute: typeof DashboardReceiptsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sync': {
      id: '/dashboard/sync'
      path: '/sync'
      fullPath: '/dashboard/sync'
      preLoaderRoute: typeof DashboardSyncRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAnimalTypesRoute: typeof DashboardAnimalTypesRoute
  DashboardBackupRoute: typeof DashboardBackupRoute
  DashboardClansRoute: typeof DashboardClansRoute
  DashboardGroupsRoute: typeof DashboardGroupsRoute
  DashboardHandoversRoute: typeof DashboardHandoversRoute
  DashboardLoansRoute: typeof DashboardLoansRoute
  DashboardObligationsRoute: typeof DashboardObligationsRoute
  DashboardParticipantsRoute: typeof DashboardParticipantsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReceiptsRoute: typeof DashboardReceiptsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSyncRoute: typeof DashboardSyncRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnimalTypesRoute: DashboardAnimalTypesRoute,
  DashboardBackupRoute: DashboardBackupRoute,
  DashboardClansRoute: DashboardClansRoute,
  DashboardGroupsRoute: DashboardGroupsRoute,
  DashboardHandoversRoute: DashboardHandoversRoute,
  DashboardLoansRoute: DashboardLoansRoute,
  DashboardObligationsRoute: DashboardObligationsRoute,
  DashboardParticipantsRoute: DashboardParticipantsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReceiptsRoute: DashboardReceiptsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSyncRoute: DashboardSyncRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
